name: fetch zenn and qiita trend

on: push
  # schedule:
  #   - cron:  '0 7 * * *' # 毎日7時に定期実行
  

env:
  TREND_QIITA_URL: ${{ secrets.TREND_QIITA_URL }}
  TREND_ZENN_URL: ${{ secrets.TREND_ZENN_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: fetch zenn qiita trend 
      run:  echo "fetch zenn,qiita trend" &&
            sed -e "s|__TREND_QIITA_URL__|${TREND_QIITA_URL}|g" 
                -e "s|__TREND_ZENN_URL__|${TREND_ZENN_URL}|g" .env.example > .env &&
            docker-compose up -d &&
            docker-compose ps