name: fetch zenn and qiita trend

on: #push
  schedule:
    - cron: '0 0 * * *' # 毎日9時に定期実行(時間がutcなので注意)
  

env:
  TREND_QIITA_URL: ${{ secrets.TREND_QIITA_URL }}
  TREND_ZENN_URL: ${{ secrets.TREND_ZENN_URL }}
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_SECRET_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout current branch #作業ブランチにchekout
      uses: actions/checkout@v2 #サードパーティの公開アクションを利用
      with:
        ref: ${{ github.ref }}
    - name: fetch zenn qiita trend 
      run:  echo "fetch zenn,qiita trend" &&
            sed -e "s|__TREND_QIITA_URL__|${TREND_QIITA_URL}|g" 
                -e "s|__TREND_ZENN_URL__|${TREND_ZENN_URL}|g" 
                -e "s|__TWITTER_API_KEY__|${TWITTER_API_KEY}|g" 
                -e "s|__TWITTER_SECRET_KEY__|${TWITTER_API_SECRET_KEY}|g" 
                -e "s|__TWITTER_ACCESS_TOKEN__|${TWITTER_ACCESS_TOKEN}|g" 
                -e "s|__TWITTER_ACCESS_TOKEN_SECRET__|${TWITTER_ACCESS_TOKEN_SECRET}|g" .env.example > .env &&
            docker-compose up -d &&
            docker-compose exec -T zenn_qiita python main.py