name: fetch zenn and qiita trend

on: push
  # schedule:
  #   - cron: '0 7 * * *' # 毎日7時に定期実行
  

env:
  TREND_QIITA_URL: ${{ secrets.TREND_QIITA_URL }}
  TREND_ZENN_URL: ${{ secrets.TREND_ZENN_URL }}
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout current branch #作業ブランチにchekout
      uses: actions/checkout@v2 #サードパーティの公開アクションを利用
      with:
        ref: ${{ github.ref }}
    - name: fetch zenn qiita trend 
      run:  echo "fetch zenn,qiita trend" &&
            sed -e "s|__TREND_QIITA_URL__|${TREND_QIITA_URL}|g" 
                -e "s|__TREND_ZENN_URL__|${TREND_ZENN_URL}|g" .env.example > .env &&
            docker-compose up -d &&
            docker-compose exec -T zenn_qiita python fetch.py 
    - name: tweet
      uses: Z-M-Huang/TweetOnAction@v1
      with:
        consumer_key: ${TWITTER_API_KEY}
        consumer_secret: ${TWITTER_API_SECRET_KEY}
        access_token: ${TWITTER_ACCESS_TOKEN}
        token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}
        content: First Tweet on GithubAction!